disabled_rules:
  - trailing_whitespace
  - line_length
  - force_cast

opt_in_rules:
  - explicit_init
  - redundant_nil_coalescing

included:
  - Sources
  - Tests

excluded:
  - Pods
  - Carthage
  - .build
